out_fn: results_clicktag/
scdb_path: data_cdna/scdb
lib: 240124_Mlei11_10x
ctmat_fn: ~/Documents/projects/mlei_development/Mlei11/data_clicktag/240124_Mlei11_10x/matrix_counts/
ctbcs_fn: ~/Documents/projects/mlei_development/Mlei11/data_clicktag/240124_Mlei11_10x/list_clicktag_barcodes.csv
cdna_lib_fn: ~/Documents/projects/mlei_development/Mlei11/data_cdna/240124_Mlei11_10x/raw_feature_bc_matrix/
cz_large_thr: 20000
cz_small_thr: 500
min_ct: 10
n_top_drops: 50000
n_amb: 1000
pval_thr: 0.001
n_sim: 1000
classification_mode: bySUM
num_ct: 2
min_bc_matches: 2
labels: ambient,ambiguous,doublet
# LDA settings 
useLDA: yes # yes/no - whether to use LDA
Posterior_prob_threshold: 0.99 # assign the droplets using this posterior probability threshold
Multiplet_rate: 0.5 # assumed proportion of multliplets among loaded cells
